title: Portfolio
email: itzdragon.contact@gmail.com
description: _
baseurl: ""
url: "https://dragonjules.github.io/Portfolio/"
twitter_username: _ItzDragon_
github_username:  DragonJules


exclude:
  - src/
  - package-lock.json
  - package.json
  - tsconfig.json


include:
  - assets/data/
  - views/